stages:
  - test

.test:
  before_script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip gfortran-8
    - gfortran --version
    - python --version
    - pip install camb

  script:
    - pip install -e .
    - python -m unittest lollipop.tests.test_lollipop

test-3.6:
  extends: .test
  stage: test
  image: python:3.6

test-3.7:
  extends: .test
  stage: test
  image: python:3.7

test-3.8:
  extends: .test
  stage: test
  image: python:3.8

test-3.9:
  extends: .test
  stage: test
  image: python:3.9
